showflick/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('showflow.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('registration/', include('django.contrib.auth.urls')),
    path('password_change/', auth_views.PasswordChangeView.as_view(
            template_name='password_reset/password_change.html',
            success_url='/'), name='password_change'),
    path('password-reset/', auth_views.PasswordResetView.as_view(
        template_name='password_reset/password_reset_form.html',
        subject_template_name='password_reset/password_reset_subject.txt',
        email_template_name='password_reset/password_reset_email.html',
        # success_url='/login/'
       ),
         name='password_reset'),
    path('password-reset/done/', auth_views.PasswordResetDoneView.as_view(
        template_name='password_reset/password_reset_done.html'), name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(
        template_name='password_reset/password_reset_confirm.html'), name='password_reset_confirm'),
    path('password-reset-complete/', auth_views.PasswordResetCompleteView.as_view(
        template_name='password_reset/password_reset_complete.html'), name='password_reset_complete'),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

showflow/urls.py
from django.urls import path
from . import views

app_name = 'showflow'

urlpatterns = [
    path('', views.home, name='home'),
    path('login/', views.login_user, name='login'),
    path('register/', views.register_user, name='register'),
    path('about/', views.about, name='about'),
    path('help/', views.help_page, name='help'),

    # Showsmovie
    path('showsmovie_list/', views.showsmovie_list, name='showsmovie_list'),
    path('showsmovie/<int:pk>/', views.showsmovie_detail, name='showsmovie_detail'),
    path('showsmovie/new/', views.showsmovie_create, name='showsmovie_create'),
    path('showsmovie/<int:pk>/edit/', views.showsmovie_edit, name='showsmovie_edit'),
    path('showsmovie/<int:pk>/delete/', views.showsmovie_delete, name='showsmovie_delete'),

    # Filter & Search Results and Search Bar
    path('send/', views.send_results, name='send_results'),
    path('search/', views.search_results, name='search_results'),

    # Actor - Genre - Streaming
    path('ags_list/', views.ags_list, name='ags_list'),
    path('actor/new/', views.actor_create, name='actor_create'),
    path('genre/new/', views.genre_create, name='genre_create'),
    path('streaming/new/', views.streaming_create, name='streaming_create'),

    path('actor/<int:pk>/update/', views.actor_edit, name='actor_edit'),
    path('genre/<int:pk>/update/', views.genre_edit, name='genre_edit'),
    path('streaming/<int:pk>/update/', views.streaming_edit, name='streaming_edit'),
    path('actor/<int:pk>/delete/', views.actor_delete, name='actor_delete'),
    path('genre/<int:pk>/delete/', views.genre_delete, name='genre_delete'),
    path('streaming/<int:pk>/delete/', views.streaming_delete, name='streaming_delete'),


]

showflow/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import Watch, Genre, Streaming, Actor


# Register user
class RegistrationForm(UserCreationForm):
    first_name = forms.CharField(max_length=101)
    last_name = forms.CharField(max_length=101)
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'password1', 'password2', 'first_name', 'last_name', 'email']

    def save(self, commit=True):
        user = super(RegistrationForm, self).save(commit=False)
        user.first_name = self.cleaned_data['first_name']
        user.last_name = self.cleaned_data['last_name']
        user.email = self.cleaned_data['email']
        if commit:
            user.save()
        return user
    

# Watch Form
class WatchForm(forms.ModelForm):
    class Meta:
        model = Watch
        fields = ['title', 'actor', 'genre', 'streaming', 'release_year', 'length', 'stars', 'rating', 'watch_type', 'url', 'description']


# Actor Form
class ActorForm(forms.ModelForm):
    class Meta:
        model = Actor
        fields = ['first_name', 'last_name']

    def clean(self):
        cleaned_data = super().clean()
        first_name = cleaned_data.get('first_name')
        last_name = cleaned_data.get('last_name')

        if Actor.objects.filter(first_name=first_name, last_name=last_name).exists():
            raise forms.ValidationError("This combination of first name and last name already exists.")

        return cleaned_data

    def clean_first_name(self):
        first_name = self.cleaned_data.get('first_name')

        if not first_name:
            raise forms.ValidationError("First name is required.")

        return first_name

    def clean_last_name(self):
        last_name = self.cleaned_data.get('last_name')

        if not last_name:
            raise forms.ValidationError("Last name is required.")

        return last_name


# Genre Form
class GenreForm(forms.ModelForm):
    class Meta:
        model = Genre
        fields = ['genre_name']

    def clean(self):
        cleaned_data = super().clean()
        genre_name = cleaned_data.get('genre_name')

        if Genre.objects.filter(genre_name=genre_name).exists():
            raise forms.ValidationError("This genre name already exists.")

        return cleaned_data

    def clean_genre_name(self):
        genre_name = self.cleaned_data.get('genre_name')

        if not genre_name:
            raise forms.ValidationError("Genre name is required.")

        return genre_name


# Streaming Form
class StreamingForm(forms.ModelForm):
    class Meta:
        model = Streaming
        fields = ['name']

    def clean(self):
        cleaned_data = super().clean()
        streaming_name = cleaned_data.get('name')

        if Streaming.objects.filter(name=streaming_name).exists():
            raise forms.ValidationError("This streaming name already exists.")

        return cleaned_data

    def clean_name(self):
        streaming_name = self.cleaned_data.get('name')

        if not streaming_name:
            raise forms.ValidationError("Streaming name is required.")

        return streaming_name

showflow/views.py
from django.contrib import messages
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.core.mail import send_mail, EmailMultiAlternatives
from django.conf import settings
from django.shortcuts import render, redirect, get_object_or_404
from django.utils.html import strip_tags
from showflow.forms import RegistrationForm, WatchForm, ActorForm, GenreForm, StreamingForm
from django.db.models import Q
from .models import Watch, Actor, Genre, Streaming
from .filters import WatchFilter


# home page
def home(request):
    return render(request, "showflow/home.html")


# about page
def about(request):
    return render(request, "showflow/about.html")


# help page
@login_required
def help_page(request):
    return render(request, "showflow/help.html")


# login
def login_user(request):
    return render(request, "registration/login.html")


# register new user
def register_user(request):
    if request.method == "POST":
        form = RegistrationForm(request.POST)
        if form.is_valid():
            username = request.POST["username"]
            email = request.POST["email"]
            subject = "Welcome to ShowFlow!"
            message = f"Hello {username} now that you have an account you can start finding shows and movies!"
            from_email = settings.EMAIL_HOST_USER
            recipient_list = [email]
            send_mail(subject, message, from_email, recipient_list, fail_silently=False)
            form.save()
            messages.success(
                request, "Your account has been created. You can log in now!"
            )
            return redirect("login")
    else:
        form = RegistrationForm()
    context = {"form": form}
    return render(request, "registration/register.html", context)


# search and filter movies and shows
# Watch show/movie List View
@login_required
def showsmovie_list(request):
    watch_all = Watch.objects.filter(user=request.user)
    watch_filter = WatchFilter(request.POST, queryset=watch_all)

    context = {
        "form": watch_filter.form,
        "watch_filter": watch_filter,
        "user": request.user
    }
    return render(request, "showflow/showsmovie_list.html", context)

# Watch show/movie Detail View
@login_required
def showsmovie_detail(request, pk):
    watch = get_object_or_404(Watch, pk=pk)

    return render(request, 'showflow/showsmovie_detail.html', {'watch': watch})

# Watch show/movie Create View
@login_required
def showsmovie_create(request):
    if request.method == 'POST':
        form = WatchForm(request.POST)
        if form.is_valid():
            watch = form.save(commit=False)
            watch.user = request.user
            watch.save()
            form.save_m2m()
            messages.success(request, f'The show/movie "{watch.title}" has been successfully added.')
            return redirect('showflow:showsmovie_list')
        else:
            messages.error(request, 'Failed to add the show/movie.')
    else:
        form = WatchForm()

    return render(request, 'showflow/showsmovie_form.html', {'form': form})

# Watch show/movie Edit View
@login_required
def showsmovie_edit(request, pk):
    watch = get_object_or_404(Watch, pk=pk)

    if request.method == 'POST':
        form = WatchForm(request.POST, instance=watch)
        if form.is_valid():
            watch = form.save(commit=False)
            watch.save()
            form.save_m2m()
            messages.success(request, f'The show/movie "{watch.title}" has been successfully updated.')
            return redirect('showflow:send_results')
        else:
            messages.error(request, 'Failed to update the show/movie.')
    else:
        form = WatchForm(instance=watch)
    return render(request, 'showflow/showsmovie_form.html', {'form': form})

# Watch show/movie Delate View
@login_required
def showsmovie_delete(request, pk):
    watch = get_object_or_404(Watch, pk=pk)

    if request.method == 'POST':
        if request.POST.get('confirm_delete') == 'True':
            watch.delete()
            messages.success(request, f'The show/movie "{watch.title}" has been successfully deleted.')
            return redirect('showflow:send_results')
        else:
            messages.error(request, 'Deletion was cancelled.')
    else:
        return render(request, 'showflow/showsmovie_delete.html', {'watch': watch})


# Actor - Genre - Streaming List
# AGS List View
def ags_list(request):
    # Model
    actors = Actor.objects.all()
    genres = Genre.objects.all()
    streamings = Streaming.objects.all()

    # Forms
    actor_form = ActorForm(request.POST)
    genre_form = GenreForm(request.POST)
    streaming_form = StreamingForm(request.POST)

    context = {
        'actors': actors,
        'genres': genres,
        'streamings': streamings,
        'actor_form': actor_form,
        'genre_form': genre_form,
        'streaming_form': streaming_form
    }

    return render(request, 'showflow/ags_list.html', context)


# Actor - Genre - Streaming
# Actor Add
def actor_create(request):
    if request.method == 'POST':
        actor_form = ActorForm(request.POST)

        if actor_form.is_valid():
            actor_form = actor_form.save(commit=False)
            actor_form.save()
            messages.success(request, f'The actor {actor_form.first_name} {actor_form.last_name} has been successfully added.')
            return redirect('showflow:ags_list')
        else:
            # Manage Form and View Messages Together
            # Extract plain text non-field errors
            non_field_errors = actor_form.non_field_errors()

            # Extract plain text field-specific errors without duplicating non-field errors
            field_errors = "\n".join([f"{strip_tags(error)}" for field, error in actor_form.errors.items() if field != '__all__'])

            # Combine non-field errors and field-specific errors
            error_messages = "\n".join([f"{error}" for error in non_field_errors] + [field_errors])

            messages.error(request, f'The actor could not be added. Please correct the following errors:\n{error_messages}')
            return redirect('showflow:ags_list')

    else:
        actor_form = ActorForm()

    context = {'actor_form': actor_form}

    return render(request, 'showflow/ags_list.html', context)

# Genre Add
def genre_create(request):
    if request.method == 'POST':
        genre_form = GenreForm(request.POST)

        if genre_form.is_valid():
            genre_form = genre_form.save(commit=False)
            genre_form.save()
            messages.success(request, f'The genre {genre_form.genre_name} has been successfully added.')
            return redirect('showflow:ags_list')
        else:
            # Manage Form and View Messages Together
            non_field_errors = genre_form.non_field_errors()
            field_errors = "\n".join([f"{strip_tags(error)}" for field, error in genre_form.errors.items() if field != '__all__'])
            error_messages = "\n".join([f"{error}" for error in non_field_errors] + [field_errors])
            messages.error(request, f'The genre could not be added. Please correct the following errors:\n{error_messages}')

            return redirect('showflow:ags_list')

    else:
        genre_form = GenreForm()

    context = {'genre_form': genre_form}

    return render(request, 'showflow/ags_list.html', context)

# Streaming Add
def streaming_create(request):
    if request.method == 'POST':
        streaming_form = StreamingForm(request.POST)

        if streaming_form.is_valid():
            streaming_form = streaming_form.save(commit=False)
            streaming_form.save()
            messages.success(request, f'The streaming {streaming_form.name} has been successfully added.')
            return redirect('showflow:ags_list')

        else:
            # Manage Form and View Messages Together
            non_field_errors = streaming_form.non_field_errors()
            field_errors = "\n".join([f"{strip_tags(error)}" for field, error in streaming_form.errors.items() if field != '__all__'])
            error_messages = "\n".join([f"{error}" for error in non_field_errors] + [field_errors])
            messages.error(request, f'The streaming could not be added. Please correct the following errors:\n{error_messages}')

            return redirect('showflow:ags_list')

    else:
        streaming_form = StreamingForm()

    context = {'streaming_form': streaming_form}

    return render(request, 'showflow/ags_list.html', context)


# Actor - Genre - Streaming Update
# Actor Update
@login_required
def actor_edit(request, pk):
    actor_fullname = get_object_or_404(Actor, pk=pk)

    if request.method == 'POST':
        actor_form = ActorForm(request.POST, instance=actor_fullname)
        if actor_form.is_valid():
            actor_form.save(commit=False)
            actor_form.save()
            messages.success(request, f'The actor has been successfully updated.')
            return redirect('showflow:ags_list')
        else:
            # Manage Form and View Messages Together
            non_field_errors = actor_form.non_field_errors()
            field_errors = "\n".join([f"{strip_tags(error)}" for field, error in actor_form.errors.items() if field != '__all__'])
            error_messages = "\n".join([f"{error}" for error in non_field_errors] + [field_errors])
            messages.error(request,f'Failed to update the actor. Please correct the following errors:\n{error_messages}')
    else:
        actor_form = ActorForm(instance=actor_fullname)

    context = {
        'actor_form': actor_form,
    }

    return render(request, 'showflow/actor_update.html', context)

# Genre Update
@login_required
def genre_edit(request, pk):
    genre = get_object_or_404(Genre, pk=pk)

    if request.method == 'POST':
        genre_form = GenreForm(request.POST, instance=genre)
        if genre_form.is_valid():

showflow/templates/showflow/actor_create.html
{% load crispy_forms_filters %}
{% load crispy_forms_tags %}
{% load static %}
    <div class="mb-5">
        <form method="post" enctype="multipart/form-data"
              action="{% if actor.id %}{% url 'showflow:actor_edit' pk=actor.pk %}{% else %}{% url 'showflow:actor_create' %}{% endif %}"
              class="form-inline">
            {% csrf_token %}
            {{ actor_form|crispy }}
            <button type="submit" class="btn btn-primary btn-sm mt-2">Add Actor</button>
        </form>
    </div>

showflow/templates/showflow/actor_delete.html
{% extends 'showflow/base.html' %}
{% load static %}
{% block title %}<title>Delete Actor</title>{% endblock title %}
{% block content %}
    <div class="container d-flex flex-column align-items-center justify-content-center vh-100">
        <h1 class="mb-4">Are you sure you want to delete "{{ actor.first_name }} {{ actor.last_name }}"?</h1>
        <form method="post" class="d-flex justify-content-center">
            {% csrf_token %}
            <input type="hidden" name="confirm_delete" value="True">
            <button type="submit" class="btn btn-danger me-3">Delete</button>
            <a href="{% url 'showflow:ags_list' %}" class="btn btn-secondary">Cancel</a>
        </form>
    </div>
{% endblock content %}

showflow/templates/showflow/ags_list.html
{% extends 'showflow/base.html' %}
{% load crispy_forms_filters %}
{% load crispy_forms_tags %}
{% load static %}
{% block styles %}
    <style>
        .backbutton {
           background-color: rgba(82, 131, 255,0.7);
           margin-top: 0.3125em;
        }
    </style>
{% endblock styles %}
{% block title %}<title>Actor - Genre - Streaming</title>{% endblock title %}
{% block content %}
    {# Back to search link #}
    <div class="d-flex ml-2 my-2">
        <a href="{% url 'showflow:showsmovie_list' %}"><button class="backbutton">Back To Search</button></a>
    </div>

    {% include 'includes/messages.html' %}

    <div class="container-fluid d-flex flex-column mb-4">
        {# Image #}
        <div class="text-center mt-4">
            <h1><img class="mb-4" src="{% static "images/showflowlogo.png" %}" alt="ShowFlow Logo" width="72" height="72"> Actor - Genre - Streaming</h1>
        </div>

        {# Actor #}
        <div class="d-flex flex-wrap justify-content-around ">
            <div class="card">
                <div class="card-body">
                    {# Add Actor #}
                    <div class="d-flex justify-content-between">
                        <h5 class="card-title">Actors</h5>
                        <a href="#" id="actorCreate"><i class="fa fa-plus" aria-hidden="true"></i></a>
                    </div>
                    <div id="actorCreateForm" style="display: none;">
                        {% include 'showflow/actor_create.html' %}
                    </div>

                    {# Display update and delete Actor #}
                    <div class="d-flex flex-column">
                        {% for actor in actors %}
                            <div class="d-flex justify-content-between align-items-center mb-2">
                                <div class="flex-grow-1">{{ actor.first_name }} {{ actor.last_name }}</div>
                                <div class="ms-3">
                                    <a href="{% url 'showflow:actor_edit' pk=actor.pk %}" class="btn btn-primary me-2"><i class="fa-regular fa-pen-to-square"></i></a>
                                    <a href="{% url 'showflow:actor_delete' pk=actor.pk %}" class="btn btn-danger"><i class="far fa-trash-alt"></i></a>
                                </div>
                            </div>
                        {% endfor %}
                    </div>
                </div>
            </div>

            {# Genre #}
            <div class="card">
                <div class="card-body">
                    {# Add Genre #}
                    <div class="d-flex justify-content-between">
                        <h5 class="card-title">Genres</h5>
                        <a href="#" id="genreCreate"><i class="fa fa-plus" aria-hidden="true"></i></a>
                    </div>
                    <div id="genreCreateForm" style="display: none;">
                        {% include 'showflow/genre_create.html' %}
                    </div>

                    {# Display update and delete Genre #}
                    <div class="d-flex flex-column">
                        {% for genre in genres %}
                            <div class="d-flex justify-content-between align-items-center mb-2">
                                <div class="flex-grow-1">{{ genre.genre_name }}</div>
                                <div class="ms-3">
                                    <a href="{% url 'showflow:genre_edit' pk=genre.pk %}" class="btn btn-primary me-2"><i class="fa-regular fa-pen-to-square"></i></a>
                                    <a href="{% url 'showflow:genre_delete' pk=genre.pk %}" class="btn btn-danger"><i class="far fa-trash-alt"></i></a>
                                </div>
                            </div>
                        {% endfor %}
                    </div>
                </div>
            </div>

            {# Streaming #}
            <div class="card">
                <div class="card-body">
                    {# Add Streaming #}
                    <div class="d-flex justify-content-between">
                        <h5 class="card-title">Streamings</h5>
                        <a href="#" id="streamingCreate"><i class="fa fa-plus" aria-hidden="true"></i></a>
                    </div>
                    <div id="streamingCreateForm" class="mb-5" style="display: none;">
                        {% include 'showflow/streaming_create.html' %}
                    </div>

                    {# Display update and delete Streaming #}
                    <div class="d-flex flex-column">
                        {% for streaming in streamings %}
                            <div class="d-flex justify-content-between align-items-center mb-2">
                                <div class="flex-grow-1">{{ streaming.name }}</div>
                                <div class="ms-3">
                                    <a href="{% url 'showflow:streaming_edit' pk=streaming.pk %}" class="btn btn-sm btn-primary me-2"><i class="fa-regular fa-pen-to-square"></i></a>
                                    <a href="{% url 'showflow:streaming_delete' pk=streaming.pk %}" class="btn btn-sm btn-danger"><i class="far fa-trash-alt"></i></a>
                                </div>
                            </div>
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>
    </div>

    <script src="{% static 'js/actorgenrestreaming.js' %}"></script>

{% endblock %}

showflow/templates/showflow/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <!-- jQuery library -->
        <script
        src="https://code.jquery.com/jquery-3.7.1.js"
        integrity="sha256-eKhayi8LEQwp4NKxN+CfCh+3qOVUtJn3QNZ0TciWLP4=" crossorigin="anonymous"></script>
        <!-- Bootstrap -->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>

        <!-- Bootstrap CSS -->
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/css/bootstrap.min.css">
        <!-- Font Awesome -->
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css" integrity="sha384-..." crossorigin="anonymous">
        <!-- add local stylesheet -->
        <link rel="stylesheet" href="{% static "css/styles.css" %}">
        {% block styles %}{% endblock styles %}

        {% block title %}<title></title>{% endblock title %}
    </head>

    {# Navigation Bar #}
    <nav class="nav navbar-light bg-dark d-flex align-items-center justify-content-center " id="myNavbar">
        <a class="navbar-brand" href="{% url 'showflow:home' %}">ShowFlow</a>
        <ul class="nav d-flex align-items-center justify-content-center ">
            <li class="nav-item ">
                <a class="nav-link" href="{% url 'showflow:home' %}">Home</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'showflow:about' %}">About</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'showflow:help' %}">Help</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'showflow:showsmovie_list' %}">Shows & Movies</a>
            </li>
        </ul>
        <!--Display Login/Logout right-justified in navbar -->
        <ul class="nav ml-auto d-flex align-items-center justify-content-center ">
            {% if user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link text-dark" href="#">Welcome, {{user.username}}</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'logout' %}"><span class="glyphicon glyphicon-log-in"></span>Logout</a>
                </li>
            {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'login' %}"><span class="glyphicon glyphicon-log-in"></span>Login</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'showflow:register' %}"><span class="glyphicon glyphicon-log-in"></span>Register</a>
                </li>
            {% endif %}

            {# Search Bar #}
            <li class="nav-item searched">
                <form class="d-flex p-2" action="{% url 'showflow:search_results' %}" method="POST" enctype='multipart/form-data'>
                    {% csrf_token %}
                    <input id="searched" class="form-control me-2" type="search" name="searched" placeholder="Search..." aria-label="Search">
                    <button style="background-color: #007bff"  type="submit" class="btn btn-info btn-sm searchedbtn" name="search">Search</button>
                </form>
            </li>
        </ul>
    </nav>
    <body>
        {% block content %}{% endblock content %}
    </body>
</html>

showflow/templates/showflow/email_results.html
{% extends 'showflow/base.html' %}
{% load crispy_forms_filters %}
{% load static %}
{% block styles %}
    <link rel="stylesheet" href="{% static "css/filter.css" %}">
{% endblock styles %}
{% block title %}<title>Filter Results</title>{% endblock title %}
{% block content %}
    <div class="container-fluid">
        {# Back to search link #}
        <div class="d-flex ml-2 my-2">
            <a href="{% url 'showflow:showsmovie_list' %}"><button class="backbutton">Back To Search</button></a>
        </div>

        {# Messages #}
        {% include 'includes/messages.html' %}

        {# Movie and show search and filter results #}
        <div id="userlist" class="d-flex flex-wrap justify-content-around align-items-center mb-5">
            <h1 style="text-align:center"><img class="mb-4" src="{% static "images/showflowlogo.png" %}" alt="ShowFlow Logo" width="72" height="72"> Search Results</h1>
            {% if watch_filter %}
                <div class="table-responsive">
                    <table class="table table-bordered table-striped text-center">
                        <tr class="header-row">
                            <th>Title</th>
                            <th>Actor</th>
                            <th>Genre</th>
                            <th>Streaming</th>
                            <th>Release Year</th>
                            <th>Length</th>
                            <th>Rating</th>
                            <th>Stars</th>
                            <th>Watch Type</th>
                            <th>Description</th>
                            <th>Details</th>
                            <th>Edit/Del</th>
                        </tr>
                        {% for watch in watch_filter.qs %}
                            <tr class="text-center">
                                <td>{{ watch.title }}</td>
                                <td>{{ watch.display_actor }}</td>
                                <td>{{ watch.display_genre }}</td>
                                <td>{{ watch.display_streaming }}</td>
                                <td>{{ watch.release_year }}</td>
                                <td>{{ watch.length }}</td>
                                <td>{{ watch.rating }}</td>
                                <td>{{ watch.stars }}</td>
                                <td>{{ watch.watch_type }}</td>
                                <td><a href="{% url 'showflow:showsmovie_detail' pk=watch.pk %}" class="btn btn-primary"><i class="fas fa-info"></i></a></td>
                                <td><a href="{{ watch.url }}" target="_blank" class="btn btn-primary"><i class="fa fa-info-circle"></i></a></td>
                                <td class="d-flex">
                                    <a href="{% url 'showflow:showsmovie_edit' pk=watch.pk %}" class="me-2 btn btn-primary"><i class="fa-regular fa-pen-to-square"></i></a>
                                    <a href="{% url 'showflow:showsmovie_delete' pk=watch.pk %}" class="btn btn-danger"><i class="far fa-trash-alt"></i></a>
                                </td>
                            </tr>
                        {% endfor %}
                    </table>
                </div>
            {% endif %}
        </div>
    </div>
{% endblock content %}

showflow/templates/showflow/genre_create.html
{% load crispy_forms_filters %}
{% load crispy_forms_tags %}
{% load static %}
    <div class="mb-5">
        <h2>Create Genre</h2>
        <form method="post" enctype="multipart/form-data" action="{% url 'showflow:genre_create' %}"
            class="form-inline">
            {% csrf_token %}
            {{ genre_form|crispy }}
            <button type="submit" class="btn btn-primary ms-2 mt-2">Add Genre</button>
        </form>
    </div>

showflow/templates/showflow/streaming_create.html
{% load crispy_forms_filters %}
{% load crispy_forms_tags %}
{% load static %}
<div>
    <h2>Create Streaming</h2>
    <form method="post" enctype="multipart/form-data" action="{% url 'showflow:streaming_create' %}"
        class="form-inline">
        {% csrf_token %}
        {{ streaming_form|crispy }}
        <button type="submit" class="btn btn-primary ms-2 mt-2">Add Streaming</button>
    </form>
</div>